#!/usr/bin/env php
<?php

require __DIR__.'/../../autoload.php';
//require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Bootstrap-app Installer', '1.0');
$app->add(new BootstrapApp\Installer\Console\NewCommand);

$app->run();